/**
 * String randomness heuristics used by the secret scanner.
 *
 * Real credentials are generated by CSPRNGs, so they have high Shannon
 * entropy and no human-friendly structure. Placeholders and dictionary
 * words score much lower, which lets us separate the two without
 * hardcoding every possible fake value.
 */

/** Shannon entropy of a string, in bits per character. */
export function shannonEntropy(s: string): number {
  if (s.length === 0) return 0;
  const freq = new Map<string, number>();
  for (const ch of s) freq.set(ch, (freq.get(ch) ?? 0) + 1);
  let entropy = 0;
  for (const count of freq.values()) {
    const p = count / s.length;
    entropy -= p * Math.log2(p);
  }
  return entropy;
}

/** True when the string contains a run of 5+ identical characters (e.g. "aaaaa", "-----"). */
export function hasLongRepeat(s: string): boolean {
  return /(.)\1{4,}/.test(s);
}

/**
 * True when the string contains a long ascending or descending character
 * run such as "abcdefgh" or "87654321" — a strong placeholder signal.
 */
export function hasSequentialRun(s: string, minRun = 8): boolean {
  let asc = 1;
  let desc = 1;
  for (let i = 1; i < s.length; i++) {
    const d = s.charCodeAt(i) - s.charCodeAt(i - 1);
    asc = d === 1 ? asc + 1 : 1;
    desc = d === -1 ? desc + 1 : 1;
    if (asc >= minRun || desc >= minRun) return true;
  }
  return false;
}
