import type { ProjectInfo } from "../types.js";
import {
  AGENT_RULES,
  buildCommandSection,
  buildStructureSummary,
} from "./agentsMd.js";

/** Generates CLAUDE.md content. */
export function generateClaudeMd(project: ProjectInfo): string {
  const name = project.packageJson?.name ?? "this project";
  return `# CLAUDE.md

Guidance for Claude when working on ${name}.

## Project

- Framework: ${project.framework}
- Package manager: ${project.packageManager}

## Commands

${buildCommandSection(project)}

## Project structure

${buildStructureSummary(project)}

## Rules

${AGENT_RULES.map((r) => `- ${r}`).join("\n")}

## Workflow

- Read existing code before writing new code.
- Verify changes compile/pass tests before declaring them done.
- Ask before making sweeping refactors.

---
Generated by [shipready](https://www.npmjs.com/package/shipready).
`;
}
