import type { ProjectInfo } from "../types.js";
import { AGENT_RULES, buildCommandSection } from "./agentsMd.js";

/** Generates .cursor/rules/shipready.md content. */
export function generateCursorRules(project: ProjectInfo): string {
  return `# shipready rules

Project: ${project.framework} (${project.packageManager})

## Commands

${buildCommandSection(project)}

## Rules for AI edits

${AGENT_RULES.map((r) => `- ${r}`).join("\n")}
- Mask or omit any secret values when displaying file contents.
- Never write real credentials into example or config files.

---
Generated by shipready.
`;
}
